// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	/**  Suggested parent folder for new worlds (`Documents\BuilderZ` by default). */
	defaultWorldsDir: () => typedError<string, AppError>(__TAURI_INVOKE("default_worlds_dir")),
	/**
	 *  Copies the file at `path` into the open world's media library, named by
	 *  its content hash. Importing the same content again returns the existing asset.
	 */
	importAsset: (path: string) => typedError<ImportedAsset, AppError>(__TAURI_INVOKE("import_asset", { path })),
	/**  Assets of the open world, newest first. */
	listAssets: (filter: AssetFilter) => typedError<Asset[], AppError>(__TAURI_INVOKE("list_assets", { filter })),
	/**  Changes the name shown for an asset (its file keeps its hash name). */
	renameAsset: (id: string, name: string) => typedError<Asset, AppError>(__TAURI_INVOKE("rename_asset", { id, name })),
	/**
	 *  Deletes an asset and its file. If it was the world's main image, the
	 *  world no longer has one.
	 */
	deleteAsset: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_asset", { id })),
	/**  App settings: preferences and recent worlds. */
	getSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("get_settings")),
	/**  Saves new preferences and returns the updated settings. */
	updatePreferences: (preferences: Preferences) => typedError<AppSettings, AppError>(__TAURI_INVOKE("update_preferences", { preferences })),
	/**
	 *  Creates a world named `name` in a new folder inside `parent_dir` (the
	 *  folder is named after the world), and opens it.
	 */
	createWorld: (parentDir: string, name: string) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("create_world", { parentDir, name })),
	/**
	 *  Opens the world in `path`, migrating it if needed. Closes the world that
	 *  was open, if any.
	 */
	openWorld: (path: string) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("open_world", { path })),
	/**  Closes the open world. Does nothing if no world is open. */
	closeWorld: () => typedError<null, AppError>(__TAURI_INVOKE("close_world")),
	/**  The open world, if any. */
	currentWorld: () => typedError<{
	id: string,
	name: string,
	genre: Genre,
	description: string,
	/**  Asset id of the main image, if any. */
	mainImage: string | null,
	/**  Absolute path of the world folder. */
	path: string,
	schemaVersion: number,
	/**  RFC 3339 dates. */
	createdAt: string,
	lastOpenedAt: string,
} | null, AppError>(__TAURI_INVOKE("current_world")),
	/**  Changes the name, genre or description of the open world. */
	updateWorld: (patch: WorldPatch) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("update_world", { patch })),
	/**  Sets (asset id) or clears (`null`) the main image of the open world. */
	setWorldMainImage: (assetId: string | null) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("set_world_main_image", { assetId })),
};

/* Types */
export type AppError = 
/**  A file system operation failed. */
{ code: "io"; message: string } | 
/**  A system directory (config, logs, data) could not be resolved. */
{ code: "path_unavailable"; message: string } | 
/**  The input sent by the front is not valid (empty name, bad path…). */
{ code: "invalid_input"; message: string } | 
/**  A world cannot be created there: the folder exists and is not empty. */
{ code: "world_already_exists"; message: string } | 
/**  The folder is not a valid BuilderZ world (missing or corrupted files). */
{ code: "world_invalid"; message: string } | 
/**  The world was saved by a newer BuilderZ; it is left untouched. */
{ code: "world_too_new"; message: string } | 
/**  The command needs an open world and none is open. */
{ code: "no_world_open"; message: string } | 
/**  A database query failed. */
{ code: "database"; message: string } | 
/**  Applying the database migrations failed; the backup is kept. */
{ code: "migration"; message: string } | 
/**  Anything that should not happen; always a bug. */
{ code: "internal"; message: string };

/**  Version and system directories of the running app. */
export type AppInfo = {
	version: string,
	configDir: string,
	dataDir: string,
	logDir: string,
};

export type AppSettings = {
	preferences: Preferences,
	/**  Most recently opened first. */
	recentWorlds: RecentWorld[],
};

/**  A file of the media library, as seen by the front. */
export type Asset = {
	/**  `<sha256>.<ext>`: file name in `assets/`, used by `useAssetUrl`. */
	id: string,
	name: string,
	kind: AssetKind,
	mime: string,
	/**  Size in bytes (u64 has no safe JS type). */
	size: number | null,
	width: number | null,
	height: number | null,
	/**  RFC 3339 import date. */
	createdAt: string,
};

/**  Filter of the media library; absent fields do not filter. */
export type AssetFilter = {
	kind?: AssetKind | null,
	/**  Fragment of the name. */
	search?: string | null,
};

export type AssetKind = "image" | "audio" | "other";

/**  Genre of a world. It decides the card types proposed by default (M2). */
export type Genre = "fantasy" | "scienceFiction" | "romance" | "cyberpunk" | "contemporary" | "other";

/**  Result of an import: the asset, and whether it is new to the world. */
export type ImportedAsset = {
	asset: Asset,
	/**  False when the same content was already in the world. */
	created: boolean,
};

export type Language = "fr" | "en";

/**  Preferences edited by the user in the settings. */
export type Preferences = {
	language: Language,
	theme: Theme,
	transparencyEffects: boolean,
};

export type RecentWorld = {
	/**  Absolute path of the world folder. */
	path: string,
	name: string,
	/**  RFC 3339 date. */
	lastOpenedAt: string,
};

export type Theme = "light" | "dark" | "system";

/**  A world as seen by the front. */
export type WorldInfo = {
	id: string,
	name: string,
	genre: Genre,
	description: string,
	/**  Asset id of the main image, if any. */
	mainImage: string | null,
	/**  Absolute path of the world folder. */
	path: string,
	schemaVersion: number,
	/**  RFC 3339 dates. */
	createdAt: string,
	lastOpenedAt: string,
};

/**  Changes to the metadata of the open world; absent fields are left as is. */
export type WorldPatch = {
	name?: string | null,
	genre?: Genre | null,
	description?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

