// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	/**
	 *  Suggested parent folder for new worlds: the one chosen in the settings,
	 *  else `Documents/BuilderZ`.
	 */
	defaultWorldsDir: () => typedError<string, AppError>(__TAURI_INVOKE("default_worlds_dir")),
	/**
	 *  Copies the file at `path` into the open world's media library, named by
	 *  its content hash. Importing the same content again returns the existing asset.
	 */
	importAsset: (path: string) => typedError<ImportedAsset, AppError>(__TAURI_INVOKE("import_asset", { path })),
	/**  Imports raw content (an image pasted from the clipboard) under `name`. */
	importAssetData: (name: string, data: number[]) => typedError<ImportedAsset, AppError>(__TAURI_INVOKE("import_asset_data", { name, data })),
	/**  Assets of the open world, newest first. */
	listAssets: (filter: AssetFilter) => typedError<Asset[], AppError>(__TAURI_INVOKE("list_assets", { filter })),
	/**  Changes the name shown for an asset (its file keeps its hash name). */
	renameAsset: (id: string, name: string) => typedError<Asset, AppError>(__TAURI_INVOKE("rename_asset", { id, name })),
	/**
	 *  Deletes an asset and its file. If it was the world's main image or theme
	 *  background, the world no longer uses it.
	 */
	deleteAsset: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_asset", { id })),
	/**  Where an asset is used, to warn before deleting it. */
	assetUsages: (id: string) => typedError<AssetUsage[], AppError>(__TAURI_INVOKE("asset_usages", { id })),
	/**  Documents of the open world, live or in the trash, by title. */
	listDocuments: (filter: DocumentFilter) => typedError<Document[], AppError>(__TAURI_INVOKE("list_documents", { filter })),
	/**  Records that a document was opened (recent documents on Home). */
	markDocumentOpened: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("mark_document_opened", { id })),
	/**  Documents opened most recently, not in the trash (at most `limit`). */
	recentDocuments: (limit: number) => typedError<RecentDocument[], AppError>(__TAURI_INVOKE("recent_documents", { limit })),
	renameDocument: (id: string, title: string) => typedError<Document, AppError>(__TAURI_INVOKE("rename_document", { id, title })),
	/**  Puts a document in the world's trash, from where it can be restored. */
	trashDocument: (id: string) => typedError<Document, AppError>(__TAURI_INVOKE("trash_document", { id })),
	restoreDocument: (id: string) => typedError<Document, AppError>(__TAURI_INVOKE("restore_document", { id })),
	/**  Deletes a document of the trash for good. */
	deleteDocument: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_document", { id })),
	/**  Deletes everything in the trash for good. Returns how many documents. */
	emptyTrash: () => typedError<number, AppError>(__TAURI_INVOKE("empty_trash")),
	/**  Card types of the open world: each type followed by its subtypes, in order. */
	listCardTypes: () => typedError<CardType[], AppError>(__TAURI_INVOKE("list_card_types")),
	/**  Creates a type, or a subtype when `parentId` is set. */
	createCardType: (cardType: NewCardType) => typedError<CardType, AppError>(__TAURI_INVOKE("create_card_type", { cardType })),
	updateCardType: (id: string, patch: CardTypePatch) => typedError<CardType, AppError>(__TAURI_INVOKE("update_card_type", { id, patch })),
	/**  Copies a type and its subtypes under a new name. */
	duplicateCardType: (id: string, name: string) => typedError<CardType, AppError>(__TAURI_INVOKE("duplicate_card_type", { id, name })),
	/**  Orders the types (or the subtypes of one type) as `ids`. */
	reorderCardTypes: (ids: string[]) => typedError<null, AppError>(__TAURI_INVOKE("reorder_card_types", { ids })),
	/**  Deletes a type and its subtypes; their cards move to `moveCardsTo`. */
	deleteCardType: (id: string, moveCardsTo: string | null) => typedError<null, AppError>(__TAURI_INVOKE("delete_card_type", { id, moveCardsTo })),
	/**
	 *  Creates a card of a type (or subtype). Rename it with `rename_document`,
	 *  put it in the trash with `trash_document`.
	 */
	createCard: (typeId: string, title: string) => typedError<Card, AppError>(__TAURI_INVOKE("create_card", { typeId, title })),
	/**  Cards of the open world (or of its trash), by title. */
	listCards: (trashed: boolean) => typedError<Card[], AppError>(__TAURI_INVOKE("list_cards", { trashed })),
	getCard: (id: string) => typedError<Card, AppError>(__TAURI_INVOKE("get_card", { id })),
	setCardType: (id: string, typeId: string) => typedError<Card, AppError>(__TAURI_INVOKE("set_card_type", { id, typeId })),
	/**  Sets (asset id) or removes (`null`) the card's image. */
	setCardImage: (id: string, assetId: string | null) => typedError<Card, AppError>(__TAURI_INVOKE("set_card_image", { id, assetId })),
	/**  Replaces the card's aliases (trimmed, without duplicates). */
	setCardAliases: (id: string, aliases: string[]) => typedError<Card, AppError>(__TAURI_INVOKE("set_card_aliases", { id, aliases })),
	/**  The card's content blocks, as JSON. */
	getCardContent: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("get_card_content", { id })),
	/**  Replaces the card's content blocks (JSON: a list of blocks). */
	setCardContent: (id: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("set_card_content", { id, content })),
	/**  Number of cards of a type and its subtypes. */
	countTypeCards: (typeId: string) => typedError<number, AppError>(__TAURI_INVOKE("count_type_cards", { typeId })),
	/**  Number of live cards per type or subtype. */
	countCardsByType: () => typedError<TypeCount[], AppError>(__TAURI_INVOKE("count_cards_by_type")),
	/**  Properties defined on a card type (not the inherited ones). */
	listTypeProperties: (typeId: string) => typedError<PropertyDefinition[], AppError>(__TAURI_INVOKE("list_type_properties", { typeId })),
	/**  The properties a card shows (its type's, then its own) with its values. */
	cardProperties: (cardId: string) => typedError<CardProperty[], AppError>(__TAURI_INVOKE("card_properties", { cardId })),
	/**  Adds a property to a type or a card. */
	createProperty: (owner: PropertyOwner, label: string, kind: PropertyKind) => typedError<PropertyDefinition, AppError>(__TAURI_INVOKE("create_property", { owner, label, kind })),
	renameProperty: (id: string, label: string) => typedError<PropertyDefinition, AppError>(__TAURI_INVOKE("rename_property", { id, label })),
	/**  Changes a property's kind; values of the old kind are dropped. */
	setPropertyKind: (id: string, kind: PropertyKind, targetTypeIds: string[]) => typedError<PropertyDefinition, AppError>(__TAURI_INVOKE("set_property_kind", { id, kind, targetTypeIds })),
	/**  Shows a type property on the cards created before it too. */
	applyPropertyToExisting: (id: string) => typedError<PropertyDefinition, AppError>(__TAURI_INVOKE("apply_property_to_existing", { id })),
	reorderProperties: (ids: string[]) => typedError<null, AppError>(__TAURI_INVOKE("reorder_properties", { ids })),
	/**  Number of values deleting the property would lose. */
	countPropertyValues: (id: string) => typedError<number, AppError>(__TAURI_INVOKE("count_property_values", { id })),
	deleteProperty: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_property", { id })),
	/**  Sets or clears (`null`) a card's value; returns the card's properties. */
	setPropertyValue: (cardId: string, propertyId: string, value: { kind: "text"; value: string } | { kind: "number"; value: number | null } | 
/**  A card id. */
{ kind: "card"; value: string } | 
/**  Card ids. */
{ kind: "cards"; value: string[] } | null) => typedError<CardProperty[], AppError>(__TAURI_INVOKE("set_property_value", { cardId, propertyId, value })),
	/**  Documents citing a card ("cited in"), with how they cite it. */
	cardBacklinks: (cardId: string) => typedError<Backlink[], AppError>(__TAURI_INVOKE("card_backlinks", { cardId })),
	/**  App settings: preferences and recent worlds. */
	getSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("get_settings")),
	/**  Saves new preferences and returns the updated settings. */
	updatePreferences: (preferences: Preferences) => typedError<AppSettings, AppError>(__TAURI_INVOKE("update_preferences", { preferences })),
	/**
	 *  Sets (absolute path) or resets (`null`) the folder proposed for new
	 *  worlds, and returns the updated settings.
	 */
	setDefaultWorldsDir: (path: string | null) => typedError<AppSettings, AppError>(__TAURI_INVOKE("set_default_worlds_dir", { path })),
	/**  Removes a world from the recent list. Its folder is not touched. */
	removeRecentWorld: (path: string) => typedError<AppSettings, AppError>(__TAURI_INVOKE("remove_recent_world", { path })),
	/**
	 *  Paths of the recent worlds whose folder no longer holds a world
	 *  (moved, renamed or deleted).
	 */
	missingRecentWorlds: () => typedError<string[], AppError>(__TAURI_INVOKE("missing_recent_worlds")),
	/**
	 *  Points a recent world whose folder moved to `new_path`, after checking
	 *  that the world there is the same one (same id).
	 */
	relocateRecentWorld: (oldPath: string, newPath: string) => typedError<AppSettings, AppError>(__TAURI_INVOKE("relocate_recent_world", { oldPath, newPath })),
	/**
	 *  Shows a world folder in the Windows Explorer. Only recent worlds are
	 *  accepted, so the front cannot make the app open arbitrary locations.
	 */
	revealInExplorer: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_in_explorer", { path })),
	/**
	 *  Creates a world named `name`, of the given genre, in a new folder inside
	 *  `parent_dir` (the folder is named after the world), and opens it.
	 */
	createWorld: (parentDir: string, name: string, genre: Genre) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("create_world", { parentDir, name, genre })),
	/**
	 *  Opens the world in `path`, migrating it if needed. Closes the world that
	 *  was open, if any.
	 */
	openWorld: (path: string) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("open_world", { path })),
	/**  Closes the open world. Does nothing if no world is open. */
	closeWorld: () => typedError<null, AppError>(__TAURI_INVOKE("close_world")),
	/**  The open world, if any. */
	currentWorld: () => typedError<{
	id: string,
	name: string,
	genre: Genre,
	description: string,
	/**  Asset id of the main image, if any. */
	mainImage: string | null,
	theme: WorldTheme,
	preferences: WorldPreferences,
	/**  Absolute path of the world folder. */
	path: string,
	schemaVersion: number,
	/**  RFC 3339 dates. */
	createdAt: string,
	lastOpenedAt: string,
} | null, AppError>(__TAURI_INVOKE("current_world")),
	/**  Changes the name, genre or description of the open world. */
	updateWorld: (patch: WorldPatch) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("update_world", { patch })),
	/**
	 *  Deletes the open world: it is closed, its folder goes to the Windows
	 *  recycle bin (it can be restored from there), and it leaves the recent
	 *  worlds. If the folder cannot be moved, the world is opened again and
	 *  nothing is lost. Returns the updated settings.
	 */
	deleteWorld: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("delete_world")),
	/**
	 *  Sets the theme of the open world (a custom background must be in the
	 *  media library).
	 */
	setWorldTheme: (theme: WorldTheme) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("set_world_theme", { theme })),
	/**  Sets the writing preferences of the open world. */
	setWorldPreferences: (preferences: WorldPreferences) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("set_world_preferences", { preferences })),
	/**  Closes the app once the front has saved its pending edits. */
	finishClose: () => typedError<null, AppError>(__TAURI_INVOKE("finish_close")),
	/**  Sets (asset id) or clears (`null`) the main image of the open world. */
	setWorldMainImage: (assetId: string | null) => typedError<WorldInfo, AppError>(__TAURI_INVOKE("set_world_main_image", { assetId })),
};

/* Types */
export type AppError = 
/**  A file system operation failed. */
{ code: "io"; message: string } | 
/**  A system directory (config, logs, data) could not be resolved. */
{ code: "path_unavailable"; message: string } | 
/**  The input sent by the front is not valid (empty name, bad path…). */
{ code: "invalid_input"; message: string } | 
/**  A world cannot be created there: the folder exists and is not empty. */
{ code: "world_already_exists"; message: string } | 
/**  The folder is not a valid BuilderZ world (missing or corrupted files). */
{ code: "world_invalid"; message: string } | 
/**  The folder holds a valid world, but not the one expected (relocation). */
{ code: "wrong_world"; message: string } | 
/**  The world was saved by a newer BuilderZ; it is left untouched. */
{ code: "world_too_new"; message: string } | 
/**  The command needs an open world and none is open. */
{ code: "no_world_open"; message: string } | 
/**  A database query failed. */
{ code: "database"; message: string } | 
/**  Applying the database migrations failed; the backup is kept. */
{ code: "migration"; message: string } | 
/**  Anything that should not happen; always a bug. */
{ code: "internal"; message: string };

/**  Version and system directories of the running app. */
export type AppInfo = {
	version: string,
	configDir: string,
	dataDir: string,
	logDir: string,
};

export type AppSettings = {
	preferences: Preferences,
	/**  Most recently opened first. */
	recentWorlds: RecentWorld[],
	/**
	 *  Folder proposed for new worlds; `None` means the default one
	 *  (`Documents/BuilderZ`, see `paths::default_worlds_dir`).
	 */
	defaultWorldsDir: string | null,
};

/**  A file of the media library, as seen by the front. */
export type Asset = {
	/**  `<sha256>.<ext>`: file name in `assets/`, used by `useAssetUrl`. */
	id: string,
	name: string,
	kind: AssetKind,
	mime: string,
	/**  Size in bytes (u64 has no safe JS type). */
	size: number | null,
	width: number | null,
	height: number | null,
	/**  RFC 3339 import date. */
	createdAt: string,
};

/**  Filter of the media library; absent fields do not filter. */
export type AssetFilter = {
	kind?: AssetKind | null,
	/**  Fragment of the name. */
	search?: string | null,
};

export type AssetKind = "image" | "audio" | "other";

/**
 *  A place where an asset is used. Grows with the modules (cards, maps,
 *  canvases…); in M1 only the world's main image uses assets.
 */
export type AssetUsage = 
/**  The main image of the open world. */
{ kind: "worldMainImage"; worldName: string } | 
/**  The background of the open world's custom theme. */
{ kind: "worldTheme"; worldName: string } | 
/**  The image of a card. */
{ kind: "cardImage"; cardId: string; cardTitle: string; inTrash: boolean } | 
/**  In an image block of a card. */
{ kind: "cardBlock"; cardId: string; cardTitle: string; inTrash: boolean };

/**  A document that cites a card, and how ("cited in" at the bottom of a card). */
export type Backlink = {
	sourceId: string,
	sourceKind: DocumentKind,
	sourceTitle: string,
	/**  For a card: its type. */
	sourceTypeId: string | null,
	/**  How the source cites the card: mentions, link properties (by label)… */
	via: BacklinkVia[],
};

export type BacklinkVia = {
	kind: LinkKind,
	/**  The property's label, for a link property. */
	propertyLabel: string | null,
};

/**  How a card of this type shows on a canvas (M7). */
export type CanvasFormat = 
/**  Name only. */
"compact" | 
/**  Image, name and type. */
"standard" | 
/**  Tall image. */
"tall" | 
/**  Wide image. */
"wide";

export type Card = {
	/**  The card's document id. */
	id: string,
	title: string,
	/**  Type or subtype; `null` only if its type vanished. */
	typeId: string | null,
	/**  Asset id of the card's image. */
	imageAssetId: string | null,
	/**  Other names, used by search and mentions. */
	aliases: string[],
	/**  RFC 3339 dates. */
	createdAt: string,
	updatedAt: string,
	/**  Set while the card is in the trash. */
	trashedAt: string | null,
};

/**  A property as a card shows it: its definition and the card's value. */
export type CardProperty = {
	definition: PropertyDefinition,
	value: PropertyValue | null,
};

export type CardType = {
	id: string,
	/**  Set for a subtype. */
	parentId: string | null,
	name: string,
	/**  lucide icon name. */
	icon: string,
	/**  One of `COLORS`. */
	color: string,
	guidedTemplate: TemplateSection[],
	orientation: Orientation,
	canvasFormat: CanvasFormat,
	sortOrder: number,
};

/**  Changes to a type; absent fields are left as is. */
export type CardTypePatch = {
	name?: string | null,
	icon?: string | null,
	color?: string | null,
	guidedTemplate?: TemplateSection[] | null,
	orientation?: Orientation | null,
	canvasFormat?: CanvasFormat | null,
};

export type Document = {
	id: string,
	kind: DocumentKind,
	title: string,
	/**  RFC 3339 dates. */
	createdAt: string,
	updatedAt: string,
	/**  Last opening, if ever. */
	openedAt: string | null,
	/**  Set while the document is in the trash. */
	trashedAt: string | null,
};

export type DocumentFilter = {
	kind?: DocumentKind | null,
	/**  The trash's content instead of the live documents. */
	trashed?: boolean,
};

export type DocumentKind = "card" | "map" | "graph" | "canvas" | "tree";

/**  Genre of a world. It decides the card types proposed by default (M2). */
export type Genre = "fantasy" | "scienceFiction" | "romance" | "cyberpunk" | "contemporary" | "other";

/**  Result of an import: the asset, and whether it is new to the world. */
export type ImportedAsset = {
	asset: Asset,
	/**  False when the same content was already in the world. */
	created: boolean,
};

export type Language = "fr" | "en";

export type LinkKind = 
/**  The card is cited in a text. */
"mention" | 
/**  The card is the value of a link property. */
"property" | 
/**  The card is pinned on a map. */
"mapPin";

export type NewCardType = {
	/**  The type to create a subtype of, or `null` for a type. */
	parentId: string | null,
	name: string,
	icon: string,
	color: string,
};

/**  Shape of the card's image. */
export type Orientation = "portrait" | "landscape";

/**  Preferences edited by the user in the settings. */
export type Preferences = {
	language: Language,
	theme: Theme,
	transparencyEffects: boolean,
	/**  Radio volume, from 0 to 100. */
	radioVolume: number,
	radioMode: RadioMode,
};

export type PropertyDefinition = {
	id: string,
	owner: PropertyOwner,
	label: string,
	kind: PropertyKind,
	/**  For links: card types allowed as targets (empty: any). */
	targetTypeIds: string[],
	/**  For a type property: whether cards created before it show it too. */
	appliesToExisting: boolean,
	sortOrder: number,
	/**  RFC 3339. */
	createdAt: string,
};

export type PropertyKind = "text" | "number" | 
/**  A link to one card. */
"card" | 
/**  Links to several cards. */
"cards";

/**  Where a property is defined. */
export type PropertyOwner = 
/**  On a card type: its cards and its subtypes' cards show it. */
{ on: "type"; typeId: string } | 
/**  On one card only. */
{ on: "card"; cardId: string };

/**  A card's value for a property. */
export type PropertyValue = { kind: "text"; value: string } | { kind: "number"; value: number | null } | 
/**  A card id. */
{ kind: "card"; value: string } | 
/**  Card ids. */
{ kind: "cards"; value: string[] };

/**  How the radio moves on at the end of a track. */
export type RadioMode = 
/**  Plays the tracks in order, then starts over. */
"loop" | 
/**  Plays the same track again. */
"repeatOne" | 
/**  Picks a random track. */
"shuffle";

/**  A document opened recently, for the Home tab. */
export type RecentDocument = {
	id: string,
	kind: DocumentKind,
	title: string,
	/**  RFC 3339. */
	openedAt: string,
	/**  For a card: its image and type. */
	imageAssetId: string | null,
	typeId: string | null,
};

export type RecentWorld = {
	/**  Absolute path of the world folder. */
	path: string,
	name: string,
	/**  World id (unknown for entries saved by 0.1.0). */
	id: string | null,
	genre: Genre | null,
	/**  Whether a thumbnail is cached (`bzthumb://<id>`). */
	thumbnail: boolean,
	/**  RFC 3339 date. */
	lastOpenedAt: string,
};

/**  A section of a guided template: a title and a question to help write it. */
export type TemplateSection = {
	title: string,
	prompt: string,
};

export type Theme = "light" | "dark" | "system";

/**  How many live cards a type (or subtype) has. */
export type TypeCount = {
	typeId: string,
	count: number,
};

/**  A world as seen by the front. */
export type WorldInfo = {
	id: string,
	name: string,
	genre: Genre,
	description: string,
	/**  Asset id of the main image, if any. */
	mainImage: string | null,
	theme: WorldTheme,
	preferences: WorldPreferences,
	/**  Absolute path of the world folder. */
	path: string,
	schemaVersion: number,
	/**  RFC 3339 dates. */
	createdAt: string,
	lastOpenedAt: string,
};

/**  Changes to the metadata of the open world; absent fields are left as is. */
export type WorldPatch = {
	name?: string | null,
	genre?: Genre | null,
	description?: string | null,
};

export type WorldPreferences = {
	/**
	 *  Card names and aliases written in text blocks are underlined, and
	 *  can be turned into mentions.
	 */
	entityDetection: boolean,
	/**
	 *  A card name or alias typed in a text block becomes a mention as soon
	 *  as the next character is typed.
	 */
	autoMentionLinks: boolean,
	/**  A mention created automatically shows with a short animation. */
	animateNewLinks: boolean,
};

export type WorldTheme = 
/**  The app's look: the main image as background, the ochre accent. */
{ kind: "default" } | 
/**
 *  A theme shipped with the app, by id (`dawn`, `forest`…). The front
 *  shows an id it does not know as the default theme.
 */
{ kind: "preset"; id: string } | 
/**  The user's own theme. */
{ kind: "custom"; 
/**  Asset id of the background image; `None`: the main image. */
background: string | null; 
/**  Accent color, `#rrggbb` in lower case. */
accent: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

