// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
};

/* Types */
export type AppError = 
/**  A file system operation failed. */
{ code: "io"; message: string } | 
/**  A system directory (config, logs, data) could not be resolved. */
{ code: "path_unavailable"; message: string } | 
/**  Anything that should not happen; always a bug. */
{ code: "internal"; message: string };

/**  Version and system directories of the running app. */
export type AppInfo = {
	version: string,
	configDir: string,
	dataDir: string,
	logDir: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

