import {
  Anchor,
  Axe,
  BookOpen,
  Bot,
  Building,
  Building2,
  Calendar,
  Castle,
  Church,
  CircuitBoard,
  Cloud,
  Coffee,
  Coins,
  Cpu,
  Crown,
  Dna,
  Drama,
  Feather,
  Flag,
  FlaskConical,
  Gem,
  Ghost,
  Globe,
  Heart,
  Home,
  Key,
  Landmark,
  Leaf,
  type LucideIcon,
  MapPin,
  Moon,
  Mountain,
  Music,
  PawPrint,
  Rocket,
  Scroll,
  Shapes,
  Shield,
  Skull,
  Sparkles,
  Star,
  StickyNote,
  Sun,
  Sword,
  Swords,
  Tent,
  TreePine,
  User,
  Users,
  Wand,
  Waves,
  Zap,
} from "lucide-react";

/**
 * Icons a card type can use, by lucide name (the value stored in the world).
 * Includes every icon of the default types (src-tauri/src/domain/card_types/defaults.rs).
 */
export const TYPE_ICONS: Record<string, LucideIcon> = {
  user: User,
  users: Users,
  "map-pin": MapPin,
  gem: Gem,
  calendar: Calendar,
  shield: Shield,
  "book-open": BookOpen,
  "sticky-note": StickyNote,
  sparkles: Sparkles,
  church: Church,
  "paw-print": PawPrint,
  leaf: Leaf,
  cpu: Cpu,
  rocket: Rocket,
  dna: Dna,
  globe: Globe,
  "building-2": Building2,
  "circuit-board": CircuitBoard,
  heart: Heart,
  coffee: Coffee,
  building: Building,
  castle: Castle,
  crown: Crown,
  sword: Sword,
  swords: Swords,
  axe: Axe,
  wand: Wand,
  "flask-conical": FlaskConical,
  scroll: Scroll,
  feather: Feather,
  flag: Flag,
  landmark: Landmark,
  mountain: Mountain,
  "tree-pine": TreePine,
  waves: Waves,
  tent: Tent,
  home: Home,
  anchor: Anchor,
  key: Key,
  coins: Coins,
  skull: Skull,
  ghost: Ghost,
  drama: Drama,
  music: Music,
  star: Star,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  zap: Zap,
  bot: Bot,
  shapes: Shapes,
};

export const TYPE_ICON_NAMES = Object.keys(TYPE_ICONS);

/** Icon of a type; a name the app does not know (newer version) falls back to a neutral one. */
export function typeIcon(name: string): LucideIcon {
  return TYPE_ICONS[name] ?? Shapes;
}
